definitions:
  services:
    docker:
      image: registry.turknet.net.tr/dockerproxy/docker:20.10.5-dind
  steps:
    - &pipeline_preparation
      name: pipeline preparation
      trigger: automatic
      image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-base-runner-prod:0.0.1
      runs-on:
        - okdprod
        - autoscaler.created
        - self.hosted
        - linux
      script:
        - sudo mkdir -p .cicd/scripts
        - sudo curl $NEXUS_PROD_URL/devops/scripts/cicd/$SCRIPT_VERSION.zip --output $SCRIPT_VERSION.zip
        - sudo unzip -d .cicd/scripts -jo $SCRIPT_VERSION.zip
        - sudo chmod +x ./.cicd/scripts/*
      artifacts:
        - .cicd/**

    - &cvm
      name: TurkNetGuard
      image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-cvm-runner:0.0.1
      runs-on:
        - okdnonprod
        - autoscaler.created
        - self.hosted
        - linux
      script:
        - ./.cicd/scripts/05_cvm.sh
      # artifacts:
      #   - pipeline.log

    - &sonar_analysis
      name: Sonar Analysis SAST
      image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-sonar-analysis-runner:0.0.1
      runs-on:
        - okdnonprod
        - autoscaler.created
        - self.hosted
        - linux
      script:
        - ./.cicd/scripts/06_sonar_analysis.sh
      # artifacts:
      #   - pipeline.log

    - &sca_analysis
      name: OWASP Dependency-Check SCA
      #image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-sca-analysis-runner:0.0.1
      runs-on:
        - nonprod
        - self.hosted
        - linux.shell
      script:
        - ./.cicd/scripts/07_sca_analysis.sh
      # artifacts:
      #   - report/**
      #   - pipeline.log

    - &dast_analysis
      name: OWASP ZAP DAST
      image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-dast-analysis-runner:0.0.1
      runs-on:
        - okdnonprod
        - autoscaler.created
        - self.hosted
        - linux
      services:
        - docker
      script:
        - ./.cicd/scripts/09_dast_analysis.sh DEV
      # artifacts:
      #   - pipeline.log

    - &trivy_analysis
      name: Trivy Analysis
      image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-trivy-analysis-runner:0.0.1
      runs-on:
        - okdnonprod
        - autoscaler.created
        - self.hosted
        - linux
      services:
        - docker
      script:
        - ./.cicd/scripts/08_trivy_analysis.sh DEV
      # artifacts:
      #   - pipeline.log

    - &endpointguard_analysis
      name: Endpoint Guard Analysis
      image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-base-runner-prod:0.0.1
      runs-on:
        - okdprod
        - autoscaler.created
        - self.hosted
        - linux
      script:
        - ./.cicd/scripts/12_endpointguard_analysis.sh PROD
      #artifacts:
      #  - pipeline.log
    - &licenguard_analysis
      name: Licen Guard Analysis
      image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-base-runner-prod:0.0.1
      runs-on:
        - okdprod
        - autoscaler.created
        - self.hosted
        - linux
      script:
        - ./.cicd/scripts/13_licenguard_analysis.sh PROD
      #artifacts:
      #  - pipeline.log

    - &security_score_check
      name: Security Scan Check
      image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-base-runner-dev:0.0.1
      runs-on:
        - okdnonprod
        - autoscaler.created
        - self.hosted
        - linux
      script:
        - ./.cicd/scripts/10_security_score_check.sh DEV
      # artifacts:
      #   - pipeline.log

    - &build_test
      name: build test env
      #image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-base-runner-dev:0.0.1
      runs-on:
        - self.hosted
        - linux.shell
        - nonprod
      script:
        - ./.cicd/scripts/02_config_manager.sh $APP_TYPE DEV
        - ./.cicd/scripts/03_docker_build_push.sh DEV
      # artifacts:
      #   - pipeline.log

    - &deploy_test
      name: deploy to test env
      image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-base-runner-dev:0.0.1
      trigger: automatic
      runs-on:
        - okdnonprod
        - autoscaler.created
        - self.hosted
        - linux
      script:
        - ./.cicd/scripts/04_okd_deploy.sh DEV
      artifacts:
        - pipeline.log

    - &build_prod
      name: build prod env
      #image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-base-runner-prod:0.0.1
      runs-on:
        - self.hosted
        - linux.shell
        - prod
      script:
        - ./.cicd/scripts/02_config_manager.sh $APP_TYPE PROD
        - ./.cicd/scripts/03_docker_build_push.sh PROD newrelic
      # artifacts:
      #   - pipeline.log

    - &deploy_prod_gyr
      name: deploy to prod env
      image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-base-runner-prod:0.0.1
      trigger: manual
      runs-on:
        - okdprod
        - autoscaler.created
        - self.hosted
        - linux
      script:
        - ./.cicd/scripts/04_okd_deploy.sh GYR
        - ./.cicd/scripts/send_deployment_info.sh
        - ./.cicd/scripts/send_deployment_info_newrelic.sh
      # artifacts:
      #   - pipeline.log

    - &deploy_prod_eqx
      name: deploy to prod env
      image: registry.turknet.net.tr/securebaseimages/runnerimages/tn-base-runner-prod:0.0.1
      trigger: manual
      runs-on:
        - okdprod
        - autoscaler.created
        - self.hosted
        - linux
      script:
        - ./.cicd/scripts/04_okd_deploy.sh EQX
        - ./.cicd/scripts/send_deployment_info.sh
        - ./.cicd/scripts/send_deployment_info_newrelic.sh
      # artifacts:
      #   - pipeline.log

pipelines:
  pull-requests:
    "**":
      - step:
          <<: *pipeline_preparation
      - stage:
          name: "Security Scan Stage for rabbitmq-ui"
          trigger: automatic
          deployment: "rabbitmq-ui-sec"
          steps:
            - step:
                <<: *cvm
            - step:
                <<: *sonar_analysis
            - step:
                <<: *sca_analysis
            - step:
                <<: *dast_analysis
            - step:
                <<: *trivy_analysis
            - step:
                <<: *endpointguard_analysis
            - step:
                <<: *licenguard_analysis
            - step:
                <<: *security_score_check

  branches:
    main:
      - step:
          <<: *pipeline_preparation
      - parallel:
          - step:
              <<: *build_prod
              name: "Build rabbitmq-ui to Prod Env"
              deployment: "rabbitmq-ui-bp"

      - parallel:
          - step:
              <<: *deploy_prod_gyr
              name: "Deploy rabbitmq-ui to Prod Env"
              deployment: "rabbitmq-ui-dpg"
              trigger: manual

    dev:
      - step:
          <<: *pipeline_preparation
      - parallel:
          - step:
              <<: *build_test
              name: "Build rabbitmq-ui to Test Env"
              deployment: "rabbitmq-ui-tb"

      - parallel:
          - step:
              <<: *deploy_test
              name: "Deploy rabbitmq-ui to Test Env"
              deployment: "rabbitmq-ui-td"

    bugfix/*:
      - step:
          <<: *pipeline_preparation
      - parallel:
          - step:
              <<: *build_test
              name: "Build rabbitmq-ui to Test Env"
              deployment: "rabbitmq-ui-tb"

      - parallel:
          - step:
              <<: *deploy_test
              name: "Deploy rabbitmq-ui to Test Env"
              deployment: "rabbitmq-ui-td"

    feature/*:
      - step:
          <<: *pipeline_preparation
      - parallel:
          - step:
              <<: *build_test
              name: "Build rabbitmq-ui to Test Env"
              deployment: "rabbitmq-ui-tb"

      - parallel:
          - step:
              <<: *deploy_test
              name: "Deploy rabbitmq-ui to Test Env"
              deployment: "rabbitmq-ui-td"
